### ISSUE TITLE
jd_ccSign.js 出错

### ISSUE THREAD

**Issue by jim114042** [Aaron-lv/sync#61]
"Timeout awaiting 'request' for 30000ms"
领券中心签到 getSign API请求失败，请检查网路重试

❗️领券中心签到, 错误!
TypeError: Cannot read properties of undefined (reading 'couponConfig')
    at /home/myid/jd/scripts/jd_ccSign.js:98:29
    at got.post.then.message (/home/myid/jd/scripts/jd_ccSign.js:323:5772)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Aaron-lv** [comment]
访问sign服务器出错，网络问题非脚本问题
