### ISSUE TITLE
jd_ccsign出错

### ISSUE THREAD

**Issue by zeldalyc** [Aaron-lv/sync#89]
近一个月运行都提示出错，检查过非网络问题，可以修复吗
领券中心签到, 错误!
TypeError: Cannot read properties of undefined (reading 'couponConfig')
    at /ql/scripts/shufflewzc_faker2/jd_ccSign.js:98:29
    at got.post.then.message (/ql/scripts/shufflewzc_faker2/jd_ccSign.js:323:5772)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Aaron-lv** [comment]
@zeldalyc 你别0点冲我的sign服务器不就好了

**Comment by zeldalyc** [comment]
其他时间运行也是一样的错误

**Comment by zeldalyc** [comment]
没有问题了

**Comment by hyzaw** [comment]
@zeldalyc 。。。
